### ISSUE TITLE
Black screen on PS3 version

### ISSUE THREAD

**Issue by realYeabokd** [StrawFox64/RSDKv5-Decompilation#1]
I installed the ps3 version i added the rsdk fike but it just gives black screen

**Comment by StrawFox64** [comment]
extracted the data.rsdk?

**Comment by realYeabokd** [comment]
> extracted the data.rsdk?

No, i just inserted the data.rsdk file.... how can i extract it?

**Comment by StrawFox64** [comment]
to be able to extract download RSDKv5 extract here. After downloading, then drag data.rsdk to RSDKv5Extract.exe and release
After you finish extracting, enter the Data folder and copy the folder from inside to console

**Comment by StrawFox64** [comment]
an update will come out that will make the files data.rsdk works, I'll close this topic
