### ISSUE TITLE
Knuckles Dies

### ISSUE THREAD

**Issue by ZacOnGH** [StrawFox64/RSDKv5-Decompilation#4]
When playing as Knuckles, you can play a special Knuckles only stage. However in this port, Knuckles just dies over and over again when loading the stage. This also happens in Encore Mode.

**Comment by StrawFox64** [comment]
It will be fixed with the update of the decompilation code. I'm working on it

**Comment by StrawFox64** [comment]
Fix in [here](https://github.com/StrawFox64/RSDKv5-Decompilation/tree/707ce5a07fed1d8c3de86825eb28f392df960bfb)
